[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_carbon_contract = "EEETpgqxVBBW7MgmhXU1iH763C2xBpBV7VmnLxjFx2Ga"


[registry]
url = "http://127.0.0.1:8899"

[provider]
cluster = "localnet"
wallet = "/Users/mohammadhosseinchinaei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"



