[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_carbon_contract = "EEETpgqxVBBW7MgmhXU1iH763C2xBpBV7VmnLxjFx2Ga"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/mohammadhosseinchinaei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"




